import { createContext  } from "react";

export const football = {
    managers: [
        {
            //1
            name:"Sir Alex Ferguson",
            date:"31 December 1941",
            active:"1974-2013",
            description:"Sir Alex is one of the best managers in football history, he is a legend of the game. He managed  Manchester United from 1986 to 2013. During his 26 years stint with Manchester United, he won 38 trophies. That includes 13 Premier League titles, five FA Cups, and two UEFA Champions League titles. He retired after the 2012/13 season, after winning the Premier League one final time.",
            clubs:"St Mirren,Aberdeen,Manchester United",
            worldCup:"0",
            clubsLeagues:"16",
            clubsChampionsLeague:"2",
            clubsEuropaLeague:"0",
            CLRunnersUp:"1",
            ELRunnersUp:"0",
            video:"https://www.youtube.com/watch?v=firT0-nbojM",
            played:"2155",
            win:"1253",
            draw:"490",
            lose:"412",
            percentage:"58.1%",
        },
        {
            //2
            name:"Jose Mourinho",
            date:"26 Januar 1963",
            active:"2000-now",
            description:"Portuguese coach José Mourinho is known for his well-organized defenses and the physical strength of his teams. He was a teacher of physical education before earning invaluable coaching experience under legends Bobby Robson and Louis Van Gaal.He has won eight league titles and four domestic cups with Porto, Chelsea, Inter, and Real Madrid. He also won the 2003 UEFA Cup and the 2004 Champions League with Porto, the 2010 Champions League with Inter, and the 2017 Europa League with Manchester United. After a mixed second spell at Chelsea, Mourinho became Manchester United manager at the start of the 2016/17 season and took them back into the Champions League by winning the 2017 Europa League. However, he was sacked at the end of 2018 after poor league form. Mourinho took over at Tottenham in 2019 but, after similarly poor league form, he returned to Italy with Roma in 2021.",
            clubs:"	União de Leiria,Porto,Chelsea,Inter,Real Madrid,Manchester United,Tottenham,AS Roma",
            worldCup:"0",
            clubsLeagues:"8",
            clubsChampionsLeague:"2",
            clubsEuropaLeague:"2",
            CLRunnersUp:"0",
            ELRunnersUp:"0",
            video:"https://www.youtube.com/watch?v=4wAG5ZUJ4eI",
            played:"1020",
            win:"648",
            draw:"206",
            lose:"166",
            percentage:"63.53%",
        },
        {
            //3
            name:"Pep Guardiola",
            date:"18 Januar 1971",
            active:"2008-now",
            description:"After a distinguished career as a defensive midfielder for Barcelona, Josep Guardiola was elevated to manager of the club's B team in 2007. One year later, he was made first team boss. After making drastic and risky changes to Barcelona's first team and footballing strategy, the club won the treble in his first season. Pep went on to win three La Liga titles, two domestic cups, three Super cups, two Champions Leagues, two European super cups, and two World club cups, claiming a total of 14 trophies in four seasons.Guardiola then took a year out to recover before becoming Bayern Munich manager in 2013. He won the domestic double in his first season, and again in 2016, but never reached a Champions League final in his three years at the club.In all, he claimed a further seven trophies with Bayern. In 2016, he took over at big-spending Manchester City and, after a season without a trophy, won the league in emphatic fashion, recording the most points, wins, and goals of any team in Premier League history. In the following season, he became the first manager to win the domestic treble. Guardiola's teams are known for keeping possession, pressing relentlessly, and their sublime creativity.",
            clubs:"Barcelona B, Barcelona,Bayern Munich, Manchester City",
            worldCup:"0",
            clubsLeagues:"9",
            clubsChampionsLeague:"2",
            clubsEuropaLeague:"0",
            CLRunnersUp:"1",
            ELRunnersUp:"0",
            video:"https://www.youtube.com/watch?v=VfKls9Eo1ZI",
            played:"770",
            win:"561",
            draw:"116",
            lose:"93",
            percentage:"72.86%",
        },
        {
            //4
            name: "Carlo Ancelotti",
            date: "10 June 1959",
            active: "1995-now",
            description: "When Carlo Ancelotti won the 2014 Champions League with Real Madrid, he became the only currently active manager to have won the tournament three times. Previously, he had won it twice with Milan in 2003 and 2007. Ancelotti's illustrious career includes league triumphs in Italy, England, France, and Germany, with Milan, Chelsea, Paris Saint-Germain, and Bayern Munich respectively. He has also claimed domestic cups with Milan, Chelsea, and Real Madrid. Ancelotti surprisingly took over at English club, Everton, in 2020 and improved their form, but he disappointed fans by leaving after one (full) season to return to Real Madrid.Ancelotti's management style is one of versatility and adaptability. He plays formations that suit the attributes of his players. With 20 trophies to his name, he is one of the most decorated managers on this list.",
            clubs: "Reggiana,Parma,Juventus,Milan,Chelsea,PSG,Real Madrid,Bayern,Napoli,Everton",
            worldCup: "0",
            clubsLeagues: "4",
            clubsChampionsLeague: "3",
            clubsEuropaLeague: "0",
            CLRunnersUp: "1",
            ELRunnersUp: "0",
            video: "https://www.youtube.com/watch?v=KyUIKAsn-sU",
            played: "1194",
            win: "694",
            draw: "275",
            lose: "225",
            percentage: "58.12%",
        },
        {
            //5
            name: "Vicente Del Bosque",
            date: "18 Januar 1971",
            active: "1999-2016",
            description: "Vicente del Bosque has helped bring unprecedented glory to Spain, winning the last two major international tournaments.But World Cup and European Championship successes aside, del Bosque also had a prolific spell in charge of Real Madrid between 1999 and 2003, winning two La Ligas and two Champions League titles.It would take a man of some standing to have turned the team of Galaticos into a highly functioning unit, but in 2003, Real Madrid stood atop the precipice of world football as a team, rather than a group of individuals.Known as a shy, reflective character who often shuns media attention, del Bosque commands respect from all who are lucky enough to play for him.'He is very important because he always makes us calm. He transmits this tranquility, this way of just not making you nervous. He has something which makes you calm and he lets you play, it makes you feel like the way you want'—Cesc Fabregas.",
            clubs: "Real Madrid, Besiktas, Spain",
            worldCup: "1",
            clubsLeagues: "2",
            clubsChampionsLeague: "2",
            clubsEuropaLeague: "0",
            CLRunnersUp: "0",
            ELRunnersUp: "0",
            video: "https://www.youtube.com/watch?v=aLRF17uzqAc",
            played: "470",
            win: "259",
            draw: "99",
            lose: "112",
            percentage: "55.11%",
        },
        {
            //6
            name: "Jurgen Klopp",
            date: "16 June 1967",
            active: "2001-now",
            description: "Liverpool manager, Jürgen Klopp, is no longer a rising star in the football world. He has well and truly arrived. Early in his career, Klopp transformed the fortunes of Borussia Dortmund, bringing them league titles in 2011 and 2012, and the German Cup in 2012. Klopp's reign ended the undisputed dominance of Bayern Munich and reestablished Dortmund as a major force in European football. He assembled an excellent team in all positions and favored a quick style of counter-attacking football that was quite similar to Arsenal (in their better years). Dortmund went on a 28-match unbeaten streak in 2012, and Klopp's side also reached the 2013 Champions League final.After taking over at Liverpool, Klopp took the club to three cup finals, including the 2018 Champions League, but was defeated in each. Klopp then won the 2019 Champions League final, beginning his trophy haul. He went on to win the UEFA Super Cup, World Club Cup, and the 2020 Premier League, the latter ending Liverpool's 30 year wait for another league triumph",
            clubs: "Mainz 05, Borussia Dortmund, Liverpool",
            worldCup: "0",
            clubsLeagues: "4",
            clubsChampionsLeague: "1",
            clubsEuropaLeague: "0",
            CLRunnersUp: "2",
            ELRunnersUp: "1",
            video: "https://www.youtube.com/watch?v=WHEthsO7T7w",
            played: "930",
            win: "495",
            draw: "224",
            lose: "211",
            percentage: "53.32%",
        },
        {
            //7
            name: "Zinedine Zidane",
            date: "23 June 1972",
            active: "2013-now",
            description: "Zinedine Zidane does not need any introduction in this list. Zidane has been one of the most successful Real Madrid managers ever in the history of the club. He is one of the greatest football managers in the world right now.Zidane became the first coach to win the Champions League three times consecutively, won the UEFA Super Cup and FIFA Club World Cup twice each, as well as a La Liga title and a Supercopa de España.His magical performance with the Real Madrid club helped him to be named Best FIFA Men’s Coach in 2017. He resigned in 2018 but later returned to the club as coach in 2019 and again won La Liga and Supercopa de España titles.However, his failure at the club in the Champions League impacted him and later Zidane left Real Madrid for a new challenge. He has won a total of 11 trophies at Real Madrid. He is number 7 in our list of top 10 best football managers in the world in 2021.",
            clubs: "Real Madrid B, Real Madrid",
            worldCup: "0",
            clubsLeagues: "2",
            clubsChampionsLeague: "3",
            clubsEuropaLeague: "0",
            CLRunnersUp: "0",
            ELRunnersUp: "0",
            video: "https://www.youtube.com/watch?v=EDeXHUp_4Uk",
            played: "320",
            win: "200",
            draw: "70",
            lose: "50",
            percentage: "62.50%",
        },
        {
            //8
            name: "Marcello Lippi",
            date: "12 April 1948",
            active: "1985-2019",
            description: "Marcello Lippi is one of the best managers in football history. Lippi led an undecorated Italian side to victory in the 2006 World Cup. He was also responsible for the domination of Italian football by Juventus in the late 1990s. Throughout his career as a manager, he won one World Cup title, five Serie A titles, three Chinese Super League titles, one Coppa Italia, one Chinese FA Cup, four Italian Supercups, one UEFA Champions League, one AFC Champions League, one UEFA Supercup, and one Intercontinental Cup. He is the first and to date the only coach to win both the UEFA Champions League and the AFC Champions League. He was named the world's best football manager by the International Federation of Football History & Statistics (IFFHS) both in 1996 and 1998, and the world's best National coach in 2006.",
            clubs: "Cesena,Lucchese,Atalanta,Napoli,Inter,Juventus,Italy,Guangzhou,China",
            worldCup: "1",
            clubsLeagues: "8",
            clubsChampionsLeague: "1",
            clubsEuropaLeague: "0",
            CLRunnersUp: "3",
            ELRunnersUp: "0",
            video: "https://www.youtube.com/watch?v=WQDvBSEigWE",
            played: "930",
            win: "449",
            draw: "270",
            lose: "211",
            percentage: "48.28%",
        },
        {
            //9
            name: "Arsene Wenger",
            date: "22 October 1949",
            active: "1984-2018",
            description: "Arsène Wenger managed Arsenal for 22 years. He advocates an attacking and flowing style of football, which made the club a favorite with neutral supporters. He has been criticized for his trust in youth and his reluctance to bring in big names. Despite a lack of recent achievements, Wenger kept Arsenal in the top group of English football for two decades, winning three league titles, seven FA Cups, and reaching the Champions League final in 2006. One of his Arsenal teams went an entire season unbeaten in 2003/04. Wenger also won a league title and domestic cup with Monaco.",
            clubs: "Monaco, Nagoya, Arsenal",
            worldCup: "0",
            clubsLeagues: "4",
            clubsChampionsLeague: "0",
            clubsEuropaLeague: "0",
            CLRunnersUp: "1",
            ELRunnersUp: "0",
            video: "https://www.youtube.com/watch?v=l87sMhkN7qk",
            played: "1.702",
            win: "919",
            draw: "367",
            lose: "416",
            percentage: "54%",
        },
        {
            //10
            name: "Jupp Heynckes",
            date: "9 May 1945",
            active: "1979-2018",
            description: "Jupp Heynckes is often the forgotten man in world football.But considering the fact that he has managed at the highest level for over 30 years, and that he won his first Bundesliga trophy in 1989, the sheer longevity of the man's career has to be admired.He is perhaps best known for winning the Champions League with Real Madrid in 1998—the first after a 32-year drought in the club's history.Now rewarded with a third stint at Bavarian giants Bayern Munich, 67 year-old Heynckes continues to prove that age is no barrier to success.'Jupp is an extraordinary coach. He has matured with age and has become more relaxed. He is just perfect'—Franz Beckenbauer.",
            clubs: "Borussia Mönchengladbach, Bayern Munich, Athletic Bilbao, Frankfurt, Tenerife, Real Madrid, Benfica, Schalke 04, Bayer Leverkusen",
            worldCup: "0",
            clubsLeagues: "4",
            clubsChampionsLeague: "2",
            clubsEuropaLeague: "0",
            CLRunnersUp: "1",
            ELRunnersUp: "0",
            video: "https://www.youtube.com/watch?v=uLjkWniuBII",
            played: "1.265",
            win: "657",
            draw: "286",
            lose: "322",
            percentage: "51.94%",
        },
    ],
    players: [
        {
            //1
            name:"Leo Messi",
            worldCup:"0",
            championsLeague:"4",
            league:"10",
            ballon:"7",
            played:"825",
            goals:"689",
            intPl:"181",
            intGl:"96",
            video:"https://www.youtube.com/watch?v=X0PI1P9p2O8",
            description:"Leo Messi considered the best player in the world and widely regarded as one of the greatest players of all time, Messi has won a record seven Ballon d'Or awards, a record six European Golden Shoes, and in 2020 was named to the Ballon d'Or Dream Team.During his time with the club, Barcelona became one of the most feared teams in world football. The Blaugrana and Messi won an incredible 35 trophies together, including ten La Liga titles, eight Spanish Super Cups, seven Copa del Rey trophies and four Champions League wins.he won a club-record 35 trophies, including ten La Liga titles, seven Copa del Rey titles and four UEFA Champions Leagues. A prolific goalscorer and creative playmaker, Messi holds the records for most goals in La Liga (474), a La Liga and European league season (50), most hat-tricks in La Liga (36) and the UEFA Champions League (8), and most assists in La Liga (192), a La Liga season (21) and the Copa América (17). He also holds the record for most international goals by a South American male (80). Messi has scored over 750 senior career goals for club and country, and has the most goals by a player for a single club. ",
            achievements:"The little magician spent 17 glorious years with Barcelona after his debut in 2004, scoring 672 goals and providing 305 assists in 778 appearances. The Argentine is inarguably the greatest player in Barcelona and La Liga history. He is also the all-time top scorer for the Spanish club and the division as well.Together with Pep Guardiola, Messi was at the heart of the greatest club football team in history - Barcelona's treble-winning team of 2009. Astonishingly, the best was yet to come. He followed that up with 91 goals in the 2012 calendar year, a frankly ridiculous record that is likely to stand for a very, very long time indeed.An Argentine international, Messi is both his country's highest appearance-maker and their all-time leading goalscorer. At youth level, he won the 2005 FIFA World Youth Championship, finishing the tournament with both the Golden Ball and Golden Shoe, and an Olympic gold medal at the 2008 Summer Olympics. His style of play as a diminutive, left-footed dribbler drew comparisons with his compatriot Diego Maradona, who described Messi as his successor. After his senior debut in August 2005, Messi became the youngest Argentine to play and score in a FIFA World Cup in 2006, and reached the final of the 2007 Copa América, where he was named young player of the tournament. As the squad's captain from August 2011, he led Argentina to three consecutive finals: the 2014 FIFA World Cup, for which he won the Golden Ball, and the 2015 and 2016 Copa América, winning the Golden Ball in the 2015 edition. After announcing his international retirement in 2016, he reversed his decision and led his country to qualification for the 2018 FIFA World Cup, a third-place finish at the 2019 Copa América, and won the 2021 Copa América, while winning the Golden Ball and Golden Boot award for the latter. This achievement would see him receive a record seventh Ballon dOr in 2021.",
        },
        {
            //2
            name:"Cristiano Ronaldo",
            worldCup:"0",
            championsLeague:"5",
            league:"7",
            ballon:"5",
            played:"915",
            goals:"687",
            intPl:"218",
            intGl:"133",
            video:"https://www.youtube.com/watch?v=OUKGsb8CpF8",
            description:"Cristiano Ronaldo often considered the best player in the world and widely regarded as one of the greatest players of all time, Ronaldo has won five Ballon d'Or awards and four European Golden Shoes, the most by a European player. He has won 32 trophies in his career, including seven league titles, five UEFA Champions Leagues, one UEFA European Championship and one UEFA Nations League. Ronaldo holds the records for most appearances (181), most goals (140) and assists (42) in the Champions League, most goals in the European Championship (14), most international goals by a male player (115), and most international appearances by a European male (184). He is one of the few players to have made over 1,100 professional career appearances, and has scored over 800 official senior career goals for club and country.",
            achievements:"Ronaldo began his senior club career playing for Sporting CP, before signing with Manchester United in 2003, aged 18, winning the FA Cup in his first season. He would also go onto win three consecutive Premier League titles, the Champions League and the FIFA Club World Cup; at age 23, he won his first Ballon d'Or. Ronaldo was the subject of the then-most expensive association football transfer when he signed for Real Madrid in 2009 in a transfer worth €94 million (£80 million), where he won 15 trophies, including two La Liga titles, two Copa del Rey and four Champions Leagues, and became the club's all-time top goalscorer. He and won back-to-back Ballons d'Or in 2013 and 2014, and again in 2016 and 2017, and was runner-up three times behind Lionel Messi, his perceived career rival. In 2018, he signed for Juventus in a transfer worth an initial €100 million (£88 million), the most expensive transfer for an Italian club and the most expensive transfer for a player over 30 years old. He won two Serie A titles, two Supercoppe Italiana and a Coppa Italia, before returning to Manchester United in 2021.Ronaldo made his senior international debut for Portugal in 2003 at the age of 18 and has since earned over 180 caps, making him Portugal's most-capped player. With more than 100 goals at international level, he is also the nation's all-time top goalscorer. He has played in and scored at 11 major tournaments; he scored his first international goal at Euro 2004, where he helped Portugal reach the final. He assumed full captaincy of the national team in July 2008. In 2015, Ronaldo was named the best Portuguese player of all time by the Portuguese Football Federation. The following year, he led Portugal to their first major tournament title at Euro 2016, and received the Silver Boot as the second-highest goalscorer of the tournament. He also led them to victory in the inaugural UEFA Nations League in 2019, and later received the Golden Boot as top scorer of Euro 2020.",
        },
        {
            //3
            name:"Zinedine Zidane",
            worldCup:"1",
            championsLeague:"1",
            league:"3",
            ballon:"0",
            played:"695",
            goals:"125",
            intPl:"108",
            intGl:"31",
            video:"https://www.youtube.com/watch?v=j4jfxEEbJMY",
            description:"Zinedine Zidane is the bridge between modern football and eras gone by. Silky and languid in possession yet powerful and efficient, Zizou was a complete midfielder. Zidane famously led France to their first World Cup trophy, scoring twice in a 3-0 demolition of Brazil in the 1998 Paris final. Two years later, France were Euro 2000 champions, with Zidane being named the Player of the Tournament.He then led them on a surprise run to the 2006 FIFA World Cup final, putting in a Man of the Match performance against Brazil in the quarter-final. Despite the heartbreak and controversy in the final, Zidane was awarded the Golden Ball for Best Player of the Tournament.",
            achievements:"Zizou's club career was equally successful. After making his name with Bordeaux, Zidane truly established himself as a global superstar with Juventus. He made 212 appearances for the Bianconeri, scoring 31 goals and assisting 38 times, and winning two Serie A titles. The highlight of Zidane's time in Italy was winning the 1998 Ballon d'Or award. He was also named the FIFA World Player of the Year in 1998 and 2000.He then completed a blockbuster transfer to Real Madrid ahead of the 2001-02 season for an enormous €76 million, a record fee at that time. The Frenchman made 227 appearances for Los Blancos, scoring 49 goals and assisting 67 strikes. Zidane was named FIFA Player of the Year again in 2003; Real Madrid won the 2002 Champions League and the 2003 La Liga title with the Frenchman.",

        },
        {
            //4
            name:"Ronaldo",
            worldCup:"2",
            championsLeague:"0",
            league:"2",
            ballon:"2",
            played:"518",
            goals:"352",
            intPl:"98",
            intGl:"62",
            video:"https://www.youtube.com/watch?v=QpqNLCg5rmg",
            description:"Ronaldo Nazario's career is one of football's biggest 'what ifs'. If not for knee injuries and hypothyroidism, the Brazilian striker could very well have established himself as the undisputed greatest player of all time.Il Fenomeno, as Ronaldo was known, received high praise from Lionel Messi, who said:'Ronaldo was my hero. He was the best striker Ive ever seen. He was so fast he could score from nothing, and could shoot the ball better than anyone.'Despite bridging bitter club rivalries while playing for Barcelona, Real Madrid, Inter Milan and AC Milan, Ronaldo remains one of football's most beloved figures.",
            achievements:"His personal accolades are even more impressive. In his career, Ronaldo clinched two Ballon d'Or titles (1997 and 2002), three FIFA World Player of the Year titles, the Golden Ball at the 1998 World Cup, the Golden Boot at the 2002 FIFA World Cup, the 1996-97 European Golden Boot, Serie A Footballer of the Year in 1998 and two Pichichi trophies.Ronaldo also scored 15 FIFA World Cup goals in 19 games, only one behind all-time top scorer Miroslav Klose. His best season in club football was his solitary year with Barcelona in 1996-97. Ronaldo scored a stunning 47 goals, and provided 12 assists in just 51 appearances. He is third in Brazil's all-time scoring list with 62 goals, behind Pele and Neymar.",
        },
        {
            //5
            name:"Ronaldinho",
            worldCup:"1",
            championsLeague:"1",
            league:"5",
            ballon:"1",
            played:"699",
            goals:"266",
            intPl:"154",
            intGl:"62",
            video:"https://www.youtube.com/watch?v=_dBz4dTZocg",
            description:"Considered one of the best players of his generation and regarded by many as one of the greatest of all time, Ronaldinho won two FIFA World Player of the Year awards and a Ballon d'Or. A global icon of the sport, he was renowned for his technical skills, creativity, dribbling ability and accuracy from free-kicks, as well as his use of tricks, feints, no-look passes and overhead kicks.At age 20, he moved to Paris Saint-Germain in France before signing for Barcelona in 2003. In his second season with Barcelona, he won his first FIFA World Player of the Year award as Barcelona won the 2004/05 La Liga title. The season that followed is considered one of the best in his career as he was integral in Barcelona winning the 2005/06 UEFA Champions League, their first in fourteen years, and another La Liga title, giving Ronaldinho his first career double, receiving the 2005 Ballon d'Or and his second FIFA World Player of the Year in the process. After scoring two spectacular solo goals in the first 2005/06 El Clásico, Ronaldinho became the second Barcelona player, after Diego Maradona in 1983, to receive a standing ovation from Real Madrid fans at the Santiago Bernabéu.Following a second-place La Liga finish to Real Madrid in the 2006/07 season and an injury-plagued 2007/08 season, Ronaldinho suffered a decline in his performances—often put down to a decrease in dedication and focus having achieved so much in the sport—and departed Barcelona to join AC Milan, where he won the 2010/11 Serie A.",
            achievements:"Ronaldinho accumulated numerous other individual awards in his career: he was included in the UEFA Team of the Year and the FIFA World XI three times each, and was named UEFA Club Footballer of the Year for the 2005/06 season and South American Footballer of the Year in 2013; in 2004, he was named by Pelé in the FIFA 100 list of the world's greatest living players.In his international career with Brazil, Ronaldinho earned 97 caps and scored 33 goals and represented his country in two FIFA World Cups. After debuting with the Seleção by winning the 1999 Copa América, he was an integral part of the 2002 FIFA World Cup-winning team, starring alongside Ronaldo and Rivaldo in an attacking trio, and was named in the FIFA World Cup All-Star Team.As captain, he led his team to the 2005 FIFA Confederations Cup title and was named man of the match in the final. He also captained the Brazil Olympic team to a bronze medal in men's football at the 2008 Summer Olympics.",
        },
        {
            //6
            name:"Iniesta",
            worldCup:"1",
            championsLeague:"4",
            league:"9",
            ballon:"0",
            played:"830",
            goals:"85",
            intPl:"131",
            intGl:"13",
            video:"https://www.youtube.com/watch?v=RIbmWdYEV18",
            description:"Andrés Iniesta is a Spanish professional footballer who plays as a midfielder. Considered one of the greatest midfielders of all time,Iniesta spent most of his career at Barcelona, where he served as the captain for three seasons.Iniesta came through La Masia, the Barcelona youth academy, and impressed from an early age.He made his first match for them in 2002 bit became their integral part during 2004-05 season where he played 37 out of 38 league games which was more than any player. He scored twice in that season and Barcelona later won that La Liga season.2009-10 La Liga was one of the best season in his career where he gained lot of critical appreciations. His performances throughout the season was lauded and he received standing ovations in both Barcelona and away grounds. Prior to the final, Manchester United manager Alex Ferguson described him as Barcelona's biggest threat. Also United's striker Wayne Rooney termed him as the best player in the world.He began playing regularly during the 2004–05 season and remained in the team until 2018. Iniesta was an integral part of the Barcelona sides that won two historic trebles in 2009 and 2015, and his 35 trophies, which includes nine La Ligas and four UEFA Champions League titles, make him the most decorated Spanish footballer of all time. After twenty-two years at Barcelona, Iniesta signed for Japanese club Vissel Kobe in 2018.",
            achievements:"Iniesta has achieved many records during his career which makes him one of the most decorated Spanish footballer of all time.He was part of the Barcelona side that won La Liga in 2004-05, 2005-06, 2008-09, 2009-10, 2010-11, 2012-13, 2014-15 and 2015-16; Copa del Rey in 2008-09, 2011-12, 2014-15, 2015-16 and 2016-17; UEFA Champions League in 2005-06, 2008-09, 2010-11 and 2014-15; FIFA Club World Cup in 2009, 2011 and 2015.For Spain he won FIFA World Cup in 2010, UEFA European Championship in 2008 and 2012.In his individual records, he was named in the UEFA Euro Team of the tournament in 2008 and 2012; La Liga Best Spanish Player in 2009; La Liga Best Attacking Midfielder in 2009, 2011, 2012, 2013 and 2014; UEFA Team of the Year in 2009, 2010, 2011, 2012, 2015 and 2016; FIFA World Dream Team in 2010; Golden Foot in 2014, FIFA Club World Cup Bronze in 2015 and many other great notable achievements in his bag.",
        },
        {
            //7
            name:"Xavi",
            worldCup:"1",
            championsLeague:"4",
            league:"9",
            ballon:"0",
            played:"945",
            goals:"113",
            intPl:"133",
            intGl:"13",
            video:"https://www.youtube.com/watch?v=7yuEt7GzbiU",
            description:"Born on January 25, 1980, in Barcelona, Catalonia, Xavier Hernandez Creus is a globally renowned footballer with around 31 international trophies - including Ballon d'Or, Olympic medals and Prince of Asturias Award.His contribution to Spain football in general and FC Barcelona in particular have been eminently notable. He currently plays as a midfielder in a Qatar based club Al Sadd SC.Xavi broke the national headlines in his first season of senior career in 1998. He scored in his debut in La Liga and made Barca victorious by 3-1. In 2004, Xavi was entitled vice-captain of the team and handled leadership with immense responsibility, helping Barcelona in winning La Liga and Supercopa de Espana for two consecutive years. He was also adjudged La Liga Spanish Player of the Year.His magical assists, creative passing techniques, and breathtaking performances earned him Player of the Tournament award at the Euro 2008. He was a major part of Barcelona's treble and scored the fourth goal in the 4–1 win in the 2009 Copa del Rey final against Athletic Bilbao.Xavi was voted 'UEFA Champions League Best Midfielder' for his contribution during Barcelona's victorious 2008-09 Champions League campaign. Xavi was La Liga's highest assisting player with 20 assists.On 2 January 2011, against Levante, Xavi made his 549th appearance for the club in all competitions, matching the record held by Migueli. Following this match, Xavi became the most veteran player for Barcelona of all time.He left Barcelona after 24 years and became a part of a Qatar club Al Sadd for three years in 2015 ",
            achievements:"Xavi has been an integral part of national team of Spain at various age stages. He played for Spain in U17, U18, U20, U21, U23 and from 2000 to 2014 in the core team. While playing in the 2000 Sydney Olympics, he was the member of silver medalist team.Xavi was named Euro 2008's Player of the Tournament after Spain defeated Germany 1–0 in the final. Besides being dominant in the midfield, Xavi was quick with his metronomic passing and his reading of the game was pivotal to Spain's success.In 2010, Spain eventually won their maiden FIFA World Cup and Xavis contribution in this venture could be estimated by the fact that he was the one who provided the most number of accurate passes, 599 with a passing success rate of 91%, and also to crossed the ball inside the 18-yard box more than any other player in the tournament.",
        },
        {
            //8
            name:"Thierry Henry",
            worldCup:"1",
            championsLeague:"1",
            league:"5",
            ballon:"0",
            played:"813",
            goals:"366",
            intPl:"123",
            intGl:"51",
            video:"https://www.youtube.com/watch?v=e89F5X0bIxE",
            description:"Henry is regarded as one of the greatest strikers in the history of the game. His football career started with Monaco's youth rank under manager Arsène Wenger. He then moved to Juventus where he majorly played as a left winger. Post 2000, Henry became a striker and one of the most feared players in Europe. He then moved to Arsenal and then to Barcelona where his team won the 'Champions League Trophy' in 2008-2009. He then moved to Major League Soccer (MLS) and performed brilliantly. His style of play has been described as ostentatious, productive, and complete. He is the only player in the history of European football to have been named the FWA 'Footballer of the Year' three times. He has also been named the 'French Player of the Year' on four occasions. Throughout his career, Henry appeared in commercials and signed many endorsements. In 2006, he was the ninth-most commercially marketable football players in the world.",
            achievements:"In 1996, Henry became France's 'Young Player of the Year' under the guidance and training of Arsène Wenger. He led France's under-18 team to 'European Championship', scoring seven goals in the competition.As a result of his splendid performance in other tournaments, he became part of the French 'FIFA World Cup' 1998 team. He continued to play for Monaco and impressed everyone with his brilliant performance. He scored 20 goals in 105 matches.In 2000, Henry's second season with Arsenal was successful as he became the team's ace goal-scorer. The team reached the finals of the 'FA Cup' but lost 2-1 to Liverpool. Henry was largely responsible for making his club a powerhouse.In 2002, Henry became the top goal-scorer of the league and scored a total of 32 goals. He played a major role in Arsenal's success and won his first silverware while playing for the club. He played against Uruguay in the World Cup finals.In 2003, he scored 32 goals in the season, which led his club to another FA Cup and he was declared man-of-the-match in the finals. He was named the 'PFA Players Player of the Year' and FWA Footballer of the Year.In 2004, he was the top scorer in the Premier League and scored 30 goals which helped Arsenal win the title without losing even a single match; the feat was last achieved 115 years ago.2005/06 turned out to be a great season for Henry. On 17 October 2005, he became the club's top goal-scorer of all time as he broke Ian Wright's record of 185 goals.He also captained his club Arsenal in their first Champions League final. In that match, Arsenal was beaten 2-1 by Barcelona. In 2007, Henry joined Barcelona for 24 million pounds.In 2009, Barcelona won the Primera Division and Champions League. Henry helped his new team win a sextuple, consisting of Supercopa de Espana, UEFA Super Cup, and the FIFA Club World Cup.In 2010, he signed a contract for multiple years with Major League Soccer club New York Bulls.",
        },
        {
            //9
            name:"Alessandro Del Piero",
            worldCup:"1",
            championsLeague:"1",
            league:"9",
            ballon:"0",
            played:"777",
            goals:"316",
            intPl:"91",
            intGl:"27",
            video:"https://www.youtube.com/watch?v=jzbGkyE70UE",
            description:"Del Piero began his professional career in 1991 with Padova of Italian Serie B. In 1993 he went to Turin club Juventus, where he has played ever since. He has been instrumental in winning the Serie A in 1995, 1997, 1998, 2002, 2003, 2005 and 2006, Champions League in 1996 and the Toyota Cup in 1996. His best season was 1997-98, when he scored 21 goals in Serie A and 10 goals in the Champions League. He is the captain of Juventus and became the Highest Scoring Juventus player, when he rounded Bonipertis 182 goals in 2005/06-sesongen. He passed 200 goals in Juve-shirt 29 0kt. 2006 in a league match against Frosinone.He is known for his powerful skuddfot and has a seemingly easy way to dribble past opponents. Journalists have described him as a player that floats in between the opponents.Free kick his top the world in which he sits with other experienced free-kick players Ronaldinho, Juninho Pernambucano, David Beckham and Roberto Carlos. The most characteristic of his free-kick, they turned inward float he takes. 10 meters outside the 16-yard box. (Known as La Zona Del Piero or Del Piero Zone.)When Juventus were demoted to Serie B Del Piero showed great loyalty to the club by choosing to stay and help the club returned to the top of Italian football.",
            achievements:"Del Piero is widely regarded as one of the greatest players of his generation and as one of the best Italian players of all time. He won the Serie A Italian Footballer of the Year award in 1998 and 2008 and received multiple nominations for the Ballon d'Or and FIFA World Player of the Year.A prolific goal-scorer, he is currently the second highest all-time Italian top-scorer in all competitions, with 346 goals, behind only Silvio Piola, with 390 goals; he is also the joint ninth highest goalscorer in Serie A history, with 188 goals.After beginning his career with Italian club Padova in Serie B in 1991, he moved to Juventus in 1993, where he played for 19 seasons (11 as captain), and holds the club records for most goals (290) and appearances (705). During his time at the club, he won six Serie A titles, the Coppa Italia, four Supercoppa Italiana titles, the UEFA Champions League, the UEFA Super Cup, the UEFA Intertoto Cup, and the Intercontinental Cup. After leaving the club in 2012, he also spent two seasons with Australian side Sydney FC; he retired in 2014, after a season with Delhi Dynamos FC in the Indian Super League.At international level, Del Piero has also represented the Italian national team at three FIFA World Cups and four UEFA European Football Championships, most notably winning the 2006 FIFA World Cup, and reaching the final of UEFA Euro 2000 with Italy. He is the joint fourth highest scorer for the Italian national team, with 27 goals, alongside Roberto Baggio, and behind only Silvio Piola with 30 goals, Giuseppe Meazza with 33 goals, and Luigi Riva with 35 goals; with 91 appearances for Italy between 1995 and 2008, he is also his nation's eleventh-most capped player of all-time. In his career Del Piero scored 462 goals.",
        },
        {
            //10
            name:"Fabio Cannavaro",
            worldCup:"1",
            championsLeague:"1",
            league:"4",
            ballon:"1",
            played:"695",
            goals:"19",
            intPl:"136",
            intGl:"2",
            video:"https://www.youtube.com/watch?v=PSPCo2-FEYw",
            description:"Fabio Cannavaro is an Italian professional football coach and former player. A centre-back, he spent the majority of his career in Italy. He started his career at Napoli before spending seven years at Parma, with whom he won two Coppa Italia titles, the 1999 Supercoppa Italiana, and the 1999 UEFA Cup. After spells at Internazionale and Juventus, he transferred (along with manager Fabio Capello) from Juventus to Real Madrid in 2006, with whom he won consecutive La Liga titles in 2007 and 2008. After returning to Juventus for one season in 2009/10, he joined Al-Ahli in Dubai, where he retired from football in 2011 after an injury-troubled season. He is regarded as one of the best defenders of all time.Cannavaro has also achieved success with the Italy national team. He helped his national team to the final of UEFA Euro 2000, being named in the team of the tournament, and became captain in 2002, following Paolo Maldini's retirement.Cannavaro led Italy to victory in the 2006 FIFA World Cup in Germany, and was given the nickname 'Il Muro di Berlino' ('The Berlin Wall') by the Italian supporters due to his defensive performances, which saw Italy keep five clean sheets and concede only two goals, neither of which were in open play. He was awarded the Silver Ball after being named the tournament's second-best player.In 2009, Cannavaro overtook Maldini as the most capped player in the country's history. He retired from international football on 25 June 2010 following Italy's failure to qualify for the knockout stages of the 2010 World Cup, having amassed 136 caps and 2 goals for the senior national team",
            achievements:"Cannavaro was named the 2006 FIFA World Player of the Year, making him the only defender in history to have won the award. He also won the Ballon d'Or award in 2006 which made him the only defender to win the award in a decade and only the third of all time after Franz Beckenbauer and Matthias Sammer.[5][6] In 2006 and 2007 Cannavaro was named in the FIFA World XI. In 2007, he was in the six man shortlist for the Laureus World Sportsman of the Year.",
        }
    ],
}

//create context
export const FootballContext = createContext(null)